### PR TITLE
EnKF Results Chapter 3

### PR DESCRIPTION
**Pull request by ksuchak1990**
This pull request contains:
* The work that I have done to adapt the Ensemble Kalman Filter to estimate both agents' locations and their destination gates around the environment based on noisy observations.
* Some notebooks to show that this works.
* A bunch of new tests/some adjustments to pre-existing tests (given that the code was written in a somewhat test-driven manner).
* Some updates to documentation
* A refactoring of the way in which we allocate destination gates to agents in `StationSim_GCS`.

If anything needs discussing then let me know.

### CODE REVIEW

**Comment by nickmalleson** [comment]
Thanks @ksuchak1990 , this is very comprehensive. I'll make some time to go through this properly, mostly for my own interest, but if there is more urgency is pulling the changes for you to continue working let me know and I'll do the merge. (P.S. Happy new year!)

**Comment by ksuchak1990** [comment]
No rush at the moment. Let me know if you have any questions when you look through it.

**Review by nickmalleson — CHANGES_REQUESTED** [review]
Amazing work Keiran! I'm going to suggest that @patricia-ternes has a quick look at the changes to the grand central parts, but only because she's more familiar with that code than I am. My only suggestion/question is whether the files in the `.ipynb_checkpoints` directories should be included too? E.g.:
[.ipynb_checkpoints/gates_agent_0_ANGLE_ADJACENT-checkpoint.pdf](https://github.com/Urban-Analytics/dust/pull/143/files#diff-981e0d05712b292f1e4a3f9969be6a4ec04d60d1451cd2f91e1f6e0a49930613)

**Comment by nickmalleson** [comment]
@patricia-ternes do you want to have a quick look at the files in this pull request that change the stationsim gcs model? E.g. [`stationsim_gcs_model.py`](https://github.com/Urban-Analytics/dust/blob/6624c70e1ebac976ffd9c681ab17fffba623d3a2/Projects/ABM_DA/stationsim/stationsim_gcs_model.py) and a couple of otthers

**Comment by ksuchak1990** [comment]
Yep, @nickmalleson those can be removed - I'll add a commit to the branch to remove them.

**Comment by ksuchak1990** [comment]
@nickmalleson - commit b1f2d65795ea4852d2ba919ba610d5685336eff4 should fix that.

**Pull request merged**
