### PR TITLE
Dev rc

### PR DESCRIPTION
**Pull request by RobertClay**
Merging UKF work for handoff.

### CODE REVIEW

**Review by nickmalleson — CHANGES_REQUESTED** [review]
Thanks for these Rob. What a lot of great work!! 

I have a couple of requests before merging this:

- could you remove the `Projects/ABM_DA/experiments/ukf_experiments/.vscode/` directory? You don't need to delete your local copy, but please  add .vscode to the main .gitignore file in the root directory so that IDE-specific files wont be synced. See https://github.com/Urban-Analytics/dust/blob/master/.gitignore (there are examples of how to exclude directories in there)

 - How large are the pickle files in `Projects/ABM_DA/experiments/ukf_experiments/pickles` ? If they're huge I'll store them with git large file storage to prevent bloating this repo. Git LFS lets you add an entire folder.

 - Are all the plots in `Projects/ABM_DA/experiments/ukf_experiments/plots/` necessary? If yes then it's fine to keep them there, but otherwise could you take them out? Some have underscores in front of their names.

 - Ditto the mp4 files. Keeping a few is fine but do we need all of them?

**Comment by RobertClay** [comment]
Hi Nick,

- .vscode removed
- pickles. any that are left are critical (for paper plots etc.) 
- likewise for plots/mp4s. I've left a few in in terms of future ideas.

**Review by nickmalleson — APPROVED** [review]
Nice one, thanks @RobertClay

**Comment by nickmalleson** [comment]
Thanks @RobertClay, these look good to me.
@ksuchak1990, Rob has made this PR to integrate his work on the Unscented Kalman Filter. I don't think that it will conflict with any of the work you're doing on stationsim, but do you want to have a quick look? I think you can get a clear enough idea just by looking at the locations of the files that have been changed rather than going through them all in detail. Let us know id you're concerned that any of the changes will affect your work

**Comment by ksuchak1990** [comment]
Thanks for copying me in @nickmalleson - I'll have a look at this first thing tomorrow morning

**Review by ksuchak1990 — APPROVED** [review]
@nickmalleson - I've just had a look through and don't think there's much that will cause problems with regards to my work as a lot of resides inside Rob's `ukf_experiments` subdirectory. I have noticed a couple of items, though, which crop up in `Projects/ABM_DA/stationsim/stationsim_gcs_model.py`:
* It looks like there has been an update to the way that exit gates are allocated to ensure that the exit gate allocated to an agent is not on the same side of the models as its entrance gate.
* It looks like there has been an update to the way that the `Model.step()` works, moving towards a setup whereby each model step represents a second, and agents are potentially moved multiple times to fill up this second's worth of time (I'm assuming that this is similar to what @patricia-ternes was referring to on #68).

Both of these look like good ideas that I'd be happy to adopt (and I don't think they'll break anything in my setup). Once this PR is resolved, I'll merge them into my branches, and update my documentation and tests to reflect the changes (although that might not be immediate).

@RobertClay - as I was scrolling through, I noticed that you might have the remnants of an unresolved merge conflict in `Projects/ABM_DA/experiments/ukf_experiments/README.md`.

**Comment by nickmalleson** [comment]
Thanks for looking at these in detail @ksuchak1990 , I'll merge them now. 

@patricia-ternes just to make you aware that there are some changes to StationSimGCS that may conflict with your current version. I know you're preparaing your own pull request; I suggest merging the latest version of the master branch into your current branch before doing the pull request as that should make it easier to identify conflicts first.

**Pull request merged**
